version: "3.9"

services:

  web:
    build: .
    command: bash -c "
               python manage.py migrate && 
               python manage.py createsuperuser-auto &&
               python manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=dbuser
      - DB_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: datingPostgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"
