version: "3.9"

services:

  web:
    build: .
    command: bash -c "
               python manage.py makemigrations &&
               python manage.py migrate && 
               python manage.py createsuperuser-auto &&
               python manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=dbuser
      - DB_PASSWORD=123
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=12345
      - BASE_URL=http://127.0.0.1:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: datingPostgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"