version: "3.9"

services:

  web:
    build: .
    container_name: datingBackend
    command: bash -c "
               python manage.py makemigrations &&
               python manage.py migrate && 
               python manage.py test &&
               python manage.py createsuperuser-auto &&
               python manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: datingPostgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    container_name: datingRedis
    ports:
      - "6379:6379"
